### ISSUE TITLE
Too long table name using PostgresDataService

### ISSUE THREAD

**Issue by NicholasNoise** [Flexberry/NewPlatform.Flexberry.ORM#13]
`PostgresDataService` seems to have a issue generating aliases for non-standard `PrimaryKeyStorage` of master tables.

Error message: `table name "ЗаявлениеНаСертифЗаявительЛично" specified more than once`
Query: [postgres_failure_long_alias.txt](https://github.com/Flexberry/NewPlatform.Flexberry.ORM/files/2265478/postgres_failure_long_alias.txt)

**Comment by NicholasNoise** [comment]
I've created PR: #14

**Comment by NicholasNoise** [comment]
ORM 4.1.0 генерирует следующий запрос:
[postgres_with_DSE_1.txt](https://github.com/Flexberry/NewPlatform.Flexberry.ORM/files/2269064/postgres_with_DSE_1.txt)
С фиксом из PR #14: 
[postgres_with_DSE_1_fix.txt](https://github.com/Flexberry/NewPlatform.Flexberry.ORM/files/2269065/postgres_with_DSE_1_fix.txt)

**Comment by bratchikov** [comment]
#20

**Comment by bratchikov** [comment]
Fixed in 4.2.0-beta02.
